<?php

$users = []; // Initialiser la variable $users pour éviter des problèmes si elle n'est pas définie plus tard

if(isset($_GET['id'])){
    // Préparez une requête SQL pour sélectionner un utilisateur en fonction de son ID
    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = ['id' => $_GET['id']];
    
    // Exécutez la requête avec les paramètres
    $query->execute($parameters);
    
    // Récupérez les informations de l'utilisateur en tant qu'array associatif
    $users = $query->fetch(PDO::FETCH_ASSOC);
}

?>

<main class="container py-5 text-center">
    <?php if (!empty($users)): ?>
        <h1><?= "{$users['first_name']} {$users['last_name']}" ?></h1>
        <h2><?= $users['email'] ?></h2>
    <?php endif; ?>
</main>

